docs_dir: _build/pydocmd
pages:
- Home: index.md
- Entities: entities.md
- References: references.md
- Operations: operations.md
- Endpoints:
    Cargo Movements: endpoints/cargo_movements.md
    Charterers: endpoints/charterers.md
    Geographies: endpoints/geographies.md
    Products: endpoints/products.md
    Vessels: endpoints/vessels.md
- Examples:
    China Loadings: examples/china.md
    Rotterdam Loadings: examples/rotterdam.md
repo_url: https://github.com/V0RT3X4/python-sdk
site_dir: _build/site
site_name: VortexaSDK
theme: readthedocs
