[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.portray.mkdocs.theme]
favicon = "art/favicon.ico"
logo = "art/favicon.ico"
name = "material"
palette = {primary = "blue grey", accent = "light blue"}