version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - restore_cache: &restore_cache
          keys:
            - v1-{{ .Branch }}-

      - run:
          name: "Install setup.py"
          command: |
            python3.7 -m venv .venv;
            . .venv/bin/activate
            pip install -U pip
            pip install -e .[tests]

      - save_cache: &save_cache
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/project/.venv
            - ~/.cache/pip

      - run:
          name: "Build docs"
          command: |
            . .venv/bin/activate
            mkdir -p ./_build/pydocmd/examples
            python docs/autogen.py
            pydocmd build

  deploy-docs:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - restore_cache: &restore_cache
          keys:
            - v1-{{ .Branch }}-
      - run:
          name: "Deploy docs if master branch"
          command: |
            . .venv/bin/activate
            mkdir -p ./_build/pydocmd/examples
            python docs/autogen.py
            pydocmd build
            pydocmd gh-deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy-docs:
          filters:
            branches:
              only:
                - ci-automation
          requires:
            - test