version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-{{ .Branch }}-

      - run:
          name: "Install requirements.txt"
          command: |
            python3.7 -m venv .venv;
            . .venv/bin/activate
            pip install -U pip
            pip install -U -r requirements.txt
            nose2

      - save_cache: &save_cache
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/project/.venv
            - ~/.cache/pip

      - run:
          name: "Run tests"
          command: |
            . .venv/bin/activate
            export SKIP_TAGS=real; nose2

      - run:
          name: "Deploy documentation to gihub pages"
          command: |
            . .venv/bin/activate
            ./docs/deploy_docs.sh

